name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9A-Za-z]+.[0-9]+'

jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_PRERELEASE: ${{ contains($GITHUB_REF, '-') }}
        with:
          tag_name: $GITHUB_REF
          release_name: $GITHUB_REF_NAME
          body: |
            ## New Feautures

             - None

            ## Refactoring

             - Plenty

            ## Fixes

             - A few

            ## Documentation

             - None

            ## Tests

             - Some

          draft: true
          prerelease: $IS_PRERELEASE
